// ============================================================
// Honeypot Fake Data Generators
// Used by Operation Overlord (crash dump) and Rolling Thunder (terminal)
// ============================================================

const HONEYPOT_SECRET = process.env.HONEYPOT_SECRET || "watchtower-overlord-key";

/**
 * Generates an HMAC-SHA256 integrity token for the honeypot form.
 * Used by server components (war-room/page.tsx) and validated by the honeypot API.
 * Edge + Node.js compatible via Web Crypto API.
 */
export async function generateIntegrityToken(fingerprint: string): Promise<string> {
    const encoder = new TextEncoder();
    const key = await crypto.subtle.importKey(
        "raw",
        encoder.encode(HONEYPOT_SECRET),
        { name: "HMAC", hash: "SHA-256" },
        false,
        ["sign"]
    );
    const signature = await crypto.subtle.sign("HMAC", key, encoder.encode(fingerprint));
    return btoa(String.fromCharCode(...new Uint8Array(signature)));
}

/**
 * Generates a fake environment dump for the Overlord crash screen.
 * Embeds the user's fingerprint fragment into fake credentials
 * to make the "leak" feel session-specific and authentic.
 *
 * Also contains the Rolling Thunder breadcrumb URL.
 */
export function generateFakeEnv(fingerprint: string): string {
    const fpPrefix = fingerprint.substring(0, 8);
    const fpSuffix = fingerprint.substring(fingerprint.length - 6);
    const ts = Math.floor(Date.now() / 1000);

    return `# ===== INTERNAL ENVIRONMENT — DO NOT EXPOSE =====
# Auto-generated by deploy pipeline v3.2.1
# Last rotated: ${new Date().toISOString().split("T")[0]}

NODE_ENV=production
NEXT_RUNTIME=edge
VERCEL_REGION=iad1
VERCEL_GIT_COMMIT_SHA=a9f3c2e7d1b845f0

# === Database ===
DATABASE_URL=postgres://watchtower_prod:${fpPrefix}_pk_live_r4nD0m@db.neon.tech:5432/watchtower
DATABASE_POOL_SIZE=20
DATABASE_SSL=require
DB_PASS=prod_viewer_fp_${fpPrefix}
DB_READ_REPLICA=postgres://readonly:${fpSuffix}_replica@db-ro.neon.tech:5432/watchtower

# === Auth ===
CLERK_SECRET_KEY=sk_live_${fpPrefix}x8Wq2mN4pR7tY
CLERK_WEBHOOK_SECRET=whsec_${fpSuffix}Kj9Lm3

# === AI / Sentinel ===
OPENAI_API_KEY=sk-proj-${fpPrefix}T5vB8nQ2wE4r
OPENAI_MODEL=gpt-4o-2024-08-06
SENTINEL_MODE=ACTIVE_DEFENSE
SENTINEL_RISK_THRESHOLD=70

# === Security ===
ARCJET_KEY=ajkey_${fpPrefix}zX3cV6bN
ARCJET_ENV=production
HONEYPOT_SECRET=wt_overlord_${fpSuffix}
RATE_LIMIT_WINDOW=60000
RATE_LIMIT_MAX=60

# === Internal Debug ===
DEBUG_ENABLED=false
MAINTENANCE_ENDPOINT=/api/__debug/session
MAINTENANCE_TOKEN=overlord
SESSION_MANAGER_VERSION=2.4.1

# ===== CRASH LOG =====
# [FATAL] SecureCommsHandler.processRequest() — Unhandled exception
# [ERROR] Integrity validation failed: token mismatch (expected HMAC, got raw)
# [ERROR] Session ${fpPrefix}... flagged for review
# [ERROR] GET /api/__debug/session?token=overlord failed: Connection reset by peer
# [ERROR] Stack trace: at InternalSessionManager.validateToken (session.ts:142)
# [ERROR]              at DebugRouter.authenticate (debug-router.ts:87)
# [ERROR]              at EdgeRuntime.handleRequest (edge.ts:23)
# [WARN]  Retry 1/3 — backoff 2000ms
# [WARN]  Retry 2/3 — backoff 4000ms
# [FATAL] Max retries exceeded. Dumping environment for incident report.
# [INFO]  Report ID: IR-${ts}-${fpPrefix}
# [INFO]  Timestamp: ${new Date().toISOString()}`;
}

/**
 * Generates a fake process list for the Rolling Thunder terminal.
 * Includes the attacker's CID and alias woven into fake processes.
 */
export function generateFakeProcessList(cid: string, alias: string): string {
    const pid = Math.floor(Math.random() * 30000) + 1000;
    return `  PID TTY          TIME CMD
    1 ?        00:05:12 systemd
    2 ?        00:00:03 kthreadd
  312 ?        00:12:44 postgres
  314 ?        00:03:21 postgres: watchtower_prod
  315 ?        00:01:18 postgres: readonly_replica
  887 ?        00:08:55 node /app/server.js
  888 ?        00:02:34 sentinel-engine --mode=active
  891 ?        00:00:47 arcjet-waf --ruleset=production
  903 ?        00:01:02 session-tracker --monitor=${cid}
  ${pid} pts/0    00:00:01 maintenance-shell [${alias}]
  ${pid + 1} ?        00:00:00 ps aux`;
}

/**
 * Generates a fake active users list for the Rolling Thunder terminal.
 * Shows the attacker's own session among fake ones.
 */
export function generateFakeUsers(cid: string, alias: string): string {
    return `Active sessions (watchtower-prod):
  SESSION          USER             STATUS      LAST ACTIVITY
  ──────────────── ──────────────── ─────────── ────────────────
  sess_a8f2c1      admin            active      2m ago
  sess_d4e7b9      sentinel-core    monitoring  <1m ago
  sess_${cid.replace("CID-", "").toLowerCase()}  ${alias.padEnd(16)} active      NOW  <-- CURRENT
  sess_7b3e21      readonly-audit   idle        15m ago
  sess_f1c8a4      backup-daemon    scheduled   1h ago

  Total: 5 active sessions | 1 maintenance session detected`;
}

/**
 * Generates a fake system status for the Rolling Thunder terminal.
 */
export function generateFakeStatus(cid: string): string {
    const upDays = Math.floor(Math.random() * 30) + 45;
    const memUsed = (Math.random() * 2 + 1.5).toFixed(1);
    const connections = Math.floor(Math.random() * 50) + 120;
    return `WATCHTOWER PRODUCTION NODE — STATUS REPORT
  ═══════════════════════════════════════════
  Hostname:     watchtower-prod-iad1
  Uptime:       ${upDays} days, 14:23:07
  Kernel:       6.1.0-18-cloud-amd64
  Runtime:      Node.js v20.11.0 (Edge)

  CPU:          4 vCPU @ 2.8GHz  [||||||||░░] 78%
  Memory:       ${memUsed}G / 4.0G      [||||||░░░░] ${Math.floor(parseFloat(memUsed) / 4 * 100)}%
  Disk:         12.3G / 20.0G    [||||||░░░░] 62%
  Network:      eth0 UP — 10.0.1.4/24

  Active DB Connections:  ${connections}
  Sentinel Engine:        ONLINE (mode: ACTIVE_DEFENSE)
  Arcjet WAF:             ONLINE (rules: 847 loaded)
  Session Monitor:        TRACKING ${cid}

  ⚠ MAINTENANCE MODE: Session granted via debug interface
  ⚠ Elevated privileges active for current terminal`;
}

/**
 * Generates a fake directory listing for the Rolling Thunder terminal.
 */
export function generateFakeDirectory(path: string): string {
    const listings: Record<string, string> = {
        "/": `total 48
drwxr-xr-x   8 root     root     4096 Feb 14 03:21 .
drwxr-xr-x   1 root     root     4096 Feb 14 03:21 ..
-rw-------   1 root     root      412 Feb 14 03:21 .env
-rw-r--r--   1 root     root     1847 Feb 10 12:00 .env.production
drwxr-xr-x   4 node     node     4096 Feb 14 03:21 app
drwxr-xr-x   2 root     root     4096 Feb 14 03:21 config
drwxr-xr-x   6 postgres postgres 4096 Feb 14 03:21 data
-rw-r--r--   1 root     root     2048 Feb 12 08:15 docker-compose.yml
drwxr-xr-x   2 root     root     4096 Feb 14 03:21 logs
-rwxr-xr-x   1 root     root      384 Feb 10 12:00 maintenance.sh
drwxr-xr-x   3 root     root     4096 Feb 14 03:21 secrets
-rw-r--r--   1 root     root      256 Feb 10 12:00 sentinel.conf`,
        "/secrets": `total 16
drwxr-xr-x  3 root root 4096 Feb 14 03:21 .
drwxr-xr-x  8 root root 4096 Feb 14 03:21 ..
-rw-------  1 root root  128 Feb 12 08:15 db_credentials.enc
-rw-------  1 root root   64 Feb 12 08:15 jwt_secret.key
-rw-------  1 root root  256 Feb 12 08:15 openai_key.enc
-rw-------  1 root root   32 Feb 12 08:15 sentinel_master.key`,
        "/logs": `total 24
drwxr-xr-x  2 root root  4096 Feb 14 03:21 .
drwxr-xr-x  8 root root  4096 Feb 14 03:21 ..
-rw-r--r--  1 root root 15847 Feb 16 10:23 access.log
-rw-r--r--  1 root root  8421 Feb 16 10:23 sentinel.log
-rw-r--r--  1 root root  3256 Feb 16 09:15 error.log
-rw-r--r--  1 root root  1024 Feb 15 22:00 audit.log`,
    };
    return listings[path] || `ls: cannot access '${path}': No such file or directory`;
}

/**
 * Generates fake file content for `cat` commands in the Rolling Thunder terminal.
 */
export function generateFakeFileContent(filepath: string, fingerprint: string): string {
    const fpPrefix = fingerprint.substring(0, 8);

    const files: Record<string, string> = {
        "/etc/passwd": `root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
node:x:1000:1000:Node.js:/home/node:/bin/bash
postgres:x:999:999:PostgreSQL:/var/lib/postgresql:/bin/bash
sentinel:x:998:998:Sentinel Engine:/opt/sentinel:/usr/sbin/nologin
watchtower:x:997:997:Watchtower Service:/app:/bin/sh`,
        ".env": `NODE_ENV=production
DATABASE_URL=postgres://watchtower_prod:${fpPrefix}_pk@db.neon.tech/watchtower
OPENAI_API_KEY=sk-proj-${fpPrefix}...redacted
CLERK_SECRET_KEY=sk_live_${fpPrefix}...redacted
ARCJET_KEY=ajkey_${fpPrefix}...redacted
SENTINEL_MODE=ACTIVE_DEFENSE`,
        "/etc/shadow": `root:$6$rounds=65536$${fpPrefix}:19769:0:99999:7:::
node:$6$rounds=65536$salt:19769:0:99999:7:::
postgres:!:19750:0:99999:7:::`,
        "sentinel.conf": `[sentinel]
mode = ACTIVE_DEFENSE
risk_threshold = 70
max_risk_score = 100
ai_model = gpt-4o-2024-08-06
log_level = INFO

[operations]
desert_storm = ENABLED
overlord = ENABLED
rolling_thunder = ARMED

[honeypot]
debug_endpoint = /api/__debug/session
maintenance_token = overlord
auto_lockdown = true`,
    };

    // Match partial paths (e.g., "cat .env" or "cat /etc/passwd")
    for (const [key, content] of Object.entries(files)) {
        if (filepath.includes(key) || filepath.endsWith(key)) {
            return content;
        }
    }
    return `cat: ${filepath}: No such file or directory`;
}
